// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:px_league/Core/hive/hive_adapters.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(FixtureAdapter());
    registerAdapter(FulltimeAdapter());
    registerAdapter(GoalsAdapter());
    registerAdapter(HomeAdapter());
    registerAdapter(LeagueAdapter());
    registerAdapter(MatchCacheModelAdapter());
    registerAdapter(MatchModelAdapter());
    registerAdapter(PeriodsAdapter());
    registerAdapter(ScoreAdapter());
    registerAdapter(StatusAdapter());
    registerAdapter(TeamsAdapter());
    registerAdapter(UserCacheModelAdapter());
    registerAdapter(UserModelAdapter());
    registerAdapter(VenueAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(FixtureAdapter());
    registerAdapter(FulltimeAdapter());
    registerAdapter(GoalsAdapter());
    registerAdapter(HomeAdapter());
    registerAdapter(LeagueAdapter());
    registerAdapter(MatchCacheModelAdapter());
    registerAdapter(MatchModelAdapter());
    registerAdapter(PeriodsAdapter());
    registerAdapter(ScoreAdapter());
    registerAdapter(StatusAdapter());
    registerAdapter(TeamsAdapter());
    registerAdapter(UserCacheModelAdapter());
    registerAdapter(UserModelAdapter());
    registerAdapter(VenueAdapter());
  }
}
