// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcHbCmsUcLBNOEjubzt5daBgFo7TuyAPU',
    appId: '1:460995459007:web:a2f2d6a21969dc4919930a',
    messagingSenderId: '460995459007',
    projectId: 'px-league',
    authDomain: 'px-league.firebaseapp.com',
    storageBucket: 'px-league.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4rBC5xFhQvbnqAulBh00s77rmVKIcUW8',
    appId: '1:460995459007:android:5edc973a9b4eaa5a19930a',
    messagingSenderId: '460995459007',
    projectId: 'px-league',
    storageBucket: 'px-league.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANqpzefPjOlJ0VIoexfqMwwU-jCBx9Gfs',
    appId: '1:460995459007:ios:a811ff9cdb73946a19930a',
    messagingSenderId: '460995459007',
    projectId: 'px-league',
    storageBucket: 'px-league.firebasestorage.app',
    iosBundleId: 'com.example.pxLeague',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANqpzefPjOlJ0VIoexfqMwwU-jCBx9Gfs',
    appId: '1:460995459007:ios:a811ff9cdb73946a19930a',
    messagingSenderId: '460995459007',
    projectId: 'px-league',
    storageBucket: 'px-league.firebasestorage.app',
    iosBundleId: 'com.example.pxLeague',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBcHbCmsUcLBNOEjubzt5daBgFo7TuyAPU',
    appId: '1:460995459007:web:e5ea41fda94e6c4c19930a',
    messagingSenderId: '460995459007',
    projectId: 'px-league',
    authDomain: 'px-league.firebaseapp.com',
    storageBucket: 'px-league.firebasestorage.app',
  );
}
